### ISSUE TITLE
A decode issues

### ISSUE THREAD

**Issue by rsj123** [d4ichi/PassGAN#6]
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    max_length=args.seq_length)
  File "/root/PassGAN-master/utils.py", line 93, in load_dataset
    for line in f:
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 3080: ordinal not in range(128)

**Comment by ghost** [comment]
go to line 92 in utils.py and add the following
```
with open(path, 'r', encoding = 'latin1') as f:
```
delete the previous one

**Comment by rsj123** [comment]
> go to line 92 in utils.py and add the following
> 
> ```
> with open(path, 'r', encoding = 'latin1') as f:
> ```
> 
> delete the previous one

I patch the bug in my fork

**Comment by ghost** [comment]
then close the issue
